taskService:
  replicaCount: 1

  image:
    repository: ghcr.io/21sam-05/devops-gitops-platform/task-service
    tag: f37768775ec8adcc320eb31ea05333559ada965e
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  probes:
    liveness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 10
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5

  autoscaling: 
    enabled: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    


notificationService:
  replicaCount: 1

  image:
    repository: ghcr.io/21sam-05/devops-gitops-platform/notification-service
    tag: f37768775ec8adcc320eb31ea05333559ada965e
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8001

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  probes:
    liveness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 10
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5


notificationServiceUrl: http://notification-service:8001

imagePullSecrets:
  - name: ghcr-secret