apiVersion: apps/v1
kind: Deployment

metadata:
  name: task-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: task-service

  template:
    metadata:
      labels:
        app: task-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: task-service
          image: ghcr.io/21sam-05/devops-gitops-platform/task-service:a879eafe2604f5821fcbaddcded7ac20f65049a9

          ports:
            - containerPort: 8000