apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-gitops-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/21sam-05/devops-gitops-platform.git
    targetRevision: main
    path: helm/devops-gitops-platform

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: task-service
      jsonPointers:
        - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true